owner: so-more
repo: proof-monitoring 

sites:
  - name: Interseed (interseed.app)
    url: https://interseed.app
  - name: Interseed Beta (try.interseed.app)
    url: https://try.interseed.app
  - name: Interseed Alpha Mirror Nᵒ1 (flutterflow.interseed.app)
    url: https://flutterflow.interseed.app
  - name: Interseed Alpha Mirror Nᵒ2 (interseed.flutterflow.app)
    url: https://interseed.flutterflow.app
  - name: Website (interseed.co.uk)
    url: https://interseed.co.uk
  - name: Website (www.interseed.co.uk)
    url: https://www.interseed.co.uk
  
assignees: # Users to assign downtime issues (optional)
  - inslayn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.interseed.app
  #baseUrl: /proof-monitoring
  logoUrl: https://wcclrbfbgolsffkzxlay.supabase.co/storage/v1/object/public/public_assets/images/interseed/interseed_icon_light.png
  name: ' '
  introTitle: Interseed is the AI-driven application that empowers entrepreneurs and small businesses to accelerate their success with less risk.
  introMessage: Harness the power of AI with Interseed to propel your business forward. Our application is designed to minimize risks and maximize success for entrepreneurs and small businesses. No need for extensive resources or technical knowledge. Let Proof do the heavy lifting, so you can focus on what you do best – growing your business.
navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
